name: Maven Build
description: Uses maven to build the code base
runs:
  using: composite
  steps:
    - name: Build with Maven
      working-directory: ./resources/base_code
      run: mvn -B package --file pom.xml
      shell: bash
